version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/jxlwqq/building-load-balancer-in-go
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...